name: PHP Unit Tests
description: Runs Laravel Unit/Feature tests, optionally with a coverage gate
inputs:
  coverage-gate:
    description: 'Enable coverage gate (true/false)'
    required: false
    default: 'false'
  coverage-threshold:
    description: 'Coverage threshold in percent (e.g. 80)'
    required: false
    default: '80'
runs:
  using: composite
  steps:
    - name: Copy environment file
      run: cp .env.example .env
      shell: bash

    - name: Generate app key
      run: php artisan key:generate
      shell: bash

    - name: Install frontend dependencies and build assets
      run: |
        npm ci
        npm run build
      shell: bash

    - name: Execute tests with coverage
      run: ./vendor/bin/phpunit --coverage-text --colors=always --no-progress > result.log
      shell: bash

    - name: Check coverage threshold
      if: inputs.coverage-gate == 'true'
      run: |
        COVERAGE=$(grep -Po 'Lines:\s+\K[0-9\.]+' result.log | head -1)
        echo "Detected coverage: $COVERAGE%"
        THRESHOLD=${{ inputs.coverage-threshold }}
        if (( $(echo "$COVERAGE < $THRESHOLD" | bc -l) )); then
          echo "Code coverage $COVERAGE% is below threshold ($THRESHOLD%)"
          exit 1
        fi
      shell: bash