# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: {{ include "master-laravel.fullname" . }}-nginx
#   namespace: {{ .Release.Namespace }}
# spec:
#   podSelector:
#     matchLabels:
#       app: {{ include "master-laravel.name" . }}
#       component: nginx
#   policyTypes:
#     - Ingress
#     - Egress
#   ingress:
#     - from:
#         - namespaceSelector: {}
#       ports:
#         - protocol: TCP
#           port: 80
#   egress:
#     - to:
#         - podSelector:
#             matchLabels:
#               app: {{ include "master-laravel.name" . }}
#               component: app
#       ports:
#         - protocol: TCP
#           port: 9000
#     - to:
#         - namespaceSelector: {}
#       ports:
#         - protocol: UDP
#           port: 53
#         - protocol: TCP
#           port: 53