apiVersion: v1
kind: Service
metadata:
  name: {{ include "master-laravel.fullname" . }}-nginx
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "master-laravel.name" . }}
    component: nginx
spec:
  type: ClusterIP
  selector:
    app: {{ include "master-laravel.name" . }}
    component: nginx
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP