
description: "Static code analysis on repository with fixed thresholds (Formats: table, sarif)"
inputs:
  severity:
    required: false
    default: "HIGH,CRITICAL"
  format:
    required: false
    default: "sarif"
  output:
    required: false
    default: ""
  path:
    required: false
    default: "."
runs:
  using: composite
  steps:
    - name: Run Trivy scan
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: fs
        scan-ref: ${{ inputs.path }}
        ignore-unfixed: true
        format: ${{ inputs.format }}
        output: ${{ inputs.output }}
        severity: ${{ inputs.severity }}
        exit-code: 1