apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "master-laravel.fullname" . }}-env
  namespace: {{ .Release.Namespace }}
data:
  .env: |
    APP_NAME=Laravel
    APP_ENV=production
    APP_KEY=base64:Yg9XmaxHPHnb7D8srw0oPNh64/kmGX+WKvYKOWFw5R4=
    APP_DEBUG=false
    APP_URL=https://master-laravel.streller.net

    APP_MAINTENANCE_DRIVER=cache

    LOG_CHANNEL=stderr
    LOG_LEVEL=info

    DB_CONNECTION=mysql
    DB_HOST={{ include "master-laravel.fullname" . }}-mysql
    DB_PORT=3306
    DB_DATABASE=laravel
    DB_USERNAME=user
    DB_PASSWORD=password

    SESSION_DRIVER=database
    SESSION_LIFETIME=120
    SESSION_ENCRYPT=true

    BROADCAST_CONNECTION=log
    FILESYSTEM_DISK=local
    QUEUE_CONNECTION=database

    CACHE_STORE=database

    REDIS_CLIENT=phpredis
    REDIS_HOST={{ include "master-laravel.fullname" . }}-redis
    REDIS_PASSWORD=null
    REDIS_PORT=6379