{{- if .Values.mysql.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "master-laravel.fullname" . }}-mysql
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "master-laravel.name" . }}
    component: mysql
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: {{ include "master-laravel.name" . }}
    component: mysql

{{- end }}