{{- if .Values.mysql.enabled }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "master-laravel.fullname" . }}-mysql
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ include "master-laravel.fullname" . }}-mysql
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "master-laravel.name" . }}
      component: mysql
  template:
    metadata:
      labels:
        app: {{ include "master-laravel.name" . }}
        component: mysql
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.rootPassword }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.user }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.password }}
            - name: MYSQL_LOG_CONSOLE
              value: "true"
          ports:
            - containerPort: 3306
              name: mysql
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.mysql.persistence.size | default "8Gi" }}

{{- end }}