{{- if .Values.redis.enabled }}

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "master-laravel.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "master-laravel.name" . }}
      component: redis
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ include "master-laravel.name" . }}
              component: redis
      ports:
        - protocol: TCP
          port: 6379
  egress:
    - {}

{{- end }}