{{- if .Values.redis.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "master-laravel.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "master-laravel.name" . }}
    component: redis
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: {{ include "master-laravel.name" . }}
    component: redis

{{- end }}