app:
  replicaCount: 1
  image:
    repository: ghcr.io/steven-streller/master-laravel-app
    tag: 1.11.8
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 750m
      memory: 1200Mi
    limits:
      cpu: 2000m
      memory: 2Gi
  autoscaling:
    minReplicas: 1
    maxReplicas: 8
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 70
nginx:
  replicaCount: 1
  image:
    repository: ghcr.io/steven-streller/master-laravel-nginx
    tag: 1.11.8
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 150m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 256Mi
  autoscaling:
    minReplicas: 1
    maxReplicas: 8
  ingress:
    enabled: true
    host: master-laravel.streller.net
    class: traefik
    tls: true
    tlsSecretName: master-laravel.streller.net
    annotations:
      cert-manager.io/cluster-issuer: cluster-issuer
mysql:
  enabled: true
  image:
    repository: mysql
    tag: 9.4.0
  rootPassword: root
  database: laravel
  user: user
  password: password
  persistence:
    size: 8Gi
redis:
  enabled: true
  image:
    repository: redis
    tag: 8.2.1-alpine3.22
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi
  persistence:
    size: 8Gi
