name: Gitleaks Check
description: Scans the repository for secrets using Gitleaks
inputs:
  fetch-depth:
    required: false
    default: "0"

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2
