name: "[CI] Build & Push Helm Chart"

on:
  push:
    branches:
      - main
    paths:
      - 'helm/**'

jobs:
  build-and-push-helm:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Helm chart
        run: helm package helm --destination .

      - name: Push Helm chart to GHCR
        run: |
          CHART_VERSION=$(grep '^version:' helm/Chart.yaml | awk '{print $2}')
          CHART_NAME=$(grep '^name:' helm/Chart.yaml | awk '{print $2}')
          helm push ${CHART_NAME}-${CHART_VERSION}.tgz oci://ghcr.io/${{ github.repository_owner }}/charts